# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ebNU2MXplOCSflYfKrKZ86bEG1x9Tufa
"""

3**211